apiVersion: v1
kind: Service
metadata:
  name: neo4j
spec:
  type: NodePort # Allows external access (like localhost:30000)
  ports:
    - port: 7474
      targetPort: 7474
      nodePort: 30074 # Access Browser at localhost:30074
      name: http
    - port: 7687
      targetPort: 7687
      nodePort: 30687 # Access Bolt at localhost:30687
      name: bolt
  selector:
    app: neo4j
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j
spec:
  serviceName: "neo4j"
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      enableServiceLinks: false
      containers:
        - name: neo4j
          image: neo4j:latest
          ports:
            - containerPort: 7474
            - containerPort: 7687
          env:
            - name: NEO4J_AUTH
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: neo4j-auth
            - name: NEO4J_dbms_memory_pagecache_size
              value: "1G"
            - name: NEO4J_dbms_memory_heap_initial__size
              value: "512m"
            - name: NEO4J_dbms_memory_heap_max__size
              value: "2G"
          volumeMounts:
            - name: neo4j-data
              mountPath: /data
            - name: neo4j-logs
              mountPath: /logs
  volumeClaimTemplates:
    - metadata:
        name: neo4j-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: neo4j-logs
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 500Mi